port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090
expreimental:
  ignore-resolve-fail: ture
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - 1.2.4.8
    - 114.114.114.114
    - 223.5.5.5
proxies:
  - name: "AWS-KR-NNR"
    type: socks5
    server: 117.185.229.112
    port: 25207
    username: admin
    password: n065946
    skip-cert-verify: true
    udp: true
  - name: "AWS-KR"
    type: socks5
    server: 15.164.151.99
    port: 57805
    username: admin
    password: n065946
    skip-cert-verify: true
    udp: true
  - name: "AWS-KR-NNR-SS"
    type: ss
    server: 117.185.229.112
    port: 25208
    cipher: dummy
    password: "n064659"
    fast_open": true
    udp: true
  - name: "AWS-KR-SS"
    type: ss
    server: 15.164.151.99
    port: 35827
    cipher: dummy
    password: "n064659"
    fast_open": true
    udp: true
  - name: "Azure-HK"
    type: socks5
    server: 183.232.230.44
    port: 30237
    username: TkYn0DLz8B
    password: "8BGF4Oz02M"
    udp: true
  - name: "AEAD"
    type: ss
    server: 15.164.151.99
    port: 36958
    cipher: aes-128-gcm
    password: "gmfaHUCUdM"
    udp: true
