proxies:
- name: "JP-v4"
  type: ss
  server: 3.115.185.52
  port: 65535
  cipher: aes-128-gcm
  password: "n064659,n065946"
  udp: true
- name: "JP-v6"
  type: ss
  server: 2406:da14:c67:8302:4f9f:c9ab:340c:b225
  port: 65535
  cipher: aes-128-gcm
  password: "n064659,n065946"
  udp: true
