port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090
expreimental:
  ignore-resolve-fail: ture
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.1
    - 114.114.114.114
proxies:
  - name: "AWS-KR"
    type: ss
    server: 15.165.149.28
    port: 18975
    cipher: dummy
    password: "gMtwTTIWRy1i"
    fast_open: true
    udp: true
  - name: "NNR-KR"
    type: ss
    server: 117.185.229.112
    port: 25208
    cipher: dummy
    password: "gMtwTTIWRy1i"
    fast_open: true
    udp: true
  - name: "AEAD-KR"
    type: ss
    server: 15.165.149.28
    port: 36958
    cipher: aes-128-gcm
    password: "gmfaHUCUdM"
    udp: true
  - name: "Azure-HK"
    type: socks5
    server: 183.232.230.44
    port: 30237
    username: TkYn0DLz8B
    password: "8BGF4Oz02M"
    udp: true
