port: 7890
socks-port: 7891
allow-lan：true
mode: Rule
log-level: silent
external-contronller: 127.0.0.1:9090
proxies:
  - name: "JP-v4"
    type: ss
    server: 35.76.246.195
    port: 65535
    cipher: aes-128-gcm
    password: "n064659,n065946"
    udp: true
  - name: "JP-v6"
    type: ss
    server: 2406:da14:c67:8302:32c8:f6b6:d851:1b04
    port: 65535
    cipher: aes-128-gcm
    password: "n064659,n065946"
    udp: true
