port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: silent
external-controller: 127.0.0.1:9090
expreimental:
  ignore-resolve-fail: ture
dns:
  enable: true
  ipv6: true
  enhanced-mode: fake-ip
  nameserver:
    - 1.1.1.1
    - 114.114.114.114
proxies:
  - name: "AWS-JP"
    type: ss
    server: 35.77.169.223
    port: 10595
    cipher: dummy
    password: "n064659,n065946"
    fast_open: true
    udp: true
