proxies:
- name: "JP-v4"
  type: ss
  server: 176.34.5.31
  port: 60000
  cipher: aes-128-gcm
  password: "n064659,n065946"
  udp: true
- name: "JP-v6"
  type: ss
  server: 2406:da14:c67:8301:2d1c:6089:dce1:f45a
  port: 60000
  cipher: aes-128-gcm
  password: "n064659,n065946"
  udp: true
