proxies:  
  - name: "🇯🇵 JP-v4"
    type: ss
    server: 35.79.191.33
    port: 52731
    cipher: 2022-blake3-aes-128-gcm
    password: eFp1zdxpsnB9RJpsr/bLcg==
    tfo: true 
    udp: true 
  - name: "🇯🇵 JP-v6"
    type: ss
    server: 2406:da14:c67:8301:26b8:b8eb:4d98:66be
    port: 52731
    cipher: 2022-blake3-aes-128-gcm
    password: eFp1zdxpsnB9RJpsr/bLcg==
    tfo: true 
    udp: true 
